[{"name": "test.test_vector_angles.VectorAngles.test_first", "status": "failed", "message": "src.vector_angles.vector_angles does not exist!", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 23, in test_first\n    a = vector_angles(A, B)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_main", "status": "errored", "message": "unexpected EOF while parsing (vector_angles.py, line 9)", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 29, in test_main\n    with patch(patch_name(module_name, \"vector_angles\"), wraps=vector_angles) as va:\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/tmc/utils.py\", line 31, in patch_name\n    getattr(importlib.import_module(m), parts[-1])\n", "  File \"/anaconda3/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\n", "  File \"<frozen importlib._bootstrap_external>\", line 781, in get_code\n", "  File \"<frozen importlib._bootstrap_external>\", line 741, in source_to_code\n", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_zero", "status": "failed", "message": "src.vector_angles.vector_angles does not exist!", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 37, in test_zero\n    a = vector_angles(A, A)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e15_vector_angles/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}]