[{"name": "test.test_row_and_column_vectors.RowsAndColumns.test_column_content", "status": "failed", "message": "src.row_and_column_vectors.get_column_vectors does not exist!", "passed": false, "points": ["p02-12.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/test/test_row_and_column_vectors.py\", line 49, in test_column_content\n    columns=get_column_vectors(a)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_row_and_column_vectors.RowsAndColumns.test_columns_types", "status": "failed", "message": "src.row_and_column_vectors.get_column_vectors does not exist!", "passed": false, "points": ["p02-12.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/test/test_row_and_column_vectors.py\", line 29, in test_columns_types\n    columns=get_column_vectors(a)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_row_and_column_vectors.RowsAndColumns.test_row_content", "status": "failed", "message": "src.row_and_column_vectors.get_row_vectors does not exist!", "passed": false, "points": ["p02-12.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/test/test_row_and_column_vectors.py\", line 39, in test_row_content\n    rows=get_row_vectors(a)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_row_and_column_vectors.RowsAndColumns.test_row_types", "status": "failed", "message": "src.row_and_column_vectors.get_row_vectors does not exist!", "passed": false, "points": ["p02-12.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/test/test_row_and_column_vectors.py\", line 22, in test_row_types\n    rows=get_row_vectors(a)\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e12_row_and_column_vectors/tmc/utils.py\", line 10, in fail\n    raise AssertionError(err)\n"]}]