[{"name": "test.test_diamond.Diamond.test_calls", "status": "failed", "message": "Expected 'eye' to have been called.", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e13_diamond/test/test_diamond.py\", line 67, in test_calls\n    peye.assert_called()\n", "  File \"/anaconda3/lib/python3.6/unittest/mock.py\", line 786, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_diamond.Diamond.test_content", "status": "failed", "message": "0.0 != 1 : Incorrect number of 1s for call 'diamond(1)'!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e13_diamond/test/test_diamond.py\", line 61, in test_content\n    msg=\"Incorrect number of 1s for call 'diamond(%i)'!\" % n)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_diamond.Diamond.test_shape", "status": "failed", "message": "Tuples differ: (0,) != (1, 1)\n\nFirst differing element 0:\n0\n1\n\nSecond tuple contains 1 additional elements.\nFirst extra element 1:\n1\n\n- (0,)\n+ (1, 1) : Incorrect shape for call 'diamond(1)'!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e13_diamond/test/test_diamond.py\", line 51, in test_shape\n    msg=\"Incorrect shape for call 'diamond(%i)'!\" % n)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 1039, in assertTupleEqual\n    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_diamond.Diamond.test_type", "status": "failed", "message": "dtype('float64') != <class 'int'> : Incorrect element type!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part02-e13_diamond/test/test_diamond.py\", line 44, in test_type\n    self.assertEqual(d.dtype, int, msg=\"Incorrect element type!\")\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]