[{"name": "test.test_stationary_distribution.StationaryDistribution.test_calls", "status": "failed", "message": "Expected 'eig' to have been called.", "passed": false, "points": ["p07-20.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e20_stationary_distribution/test/test_stationary_distribution.py\", line 43, in test_calls\n    eig.assert_called()\n", "  File \"/anaconda3/lib/python3.6/unittest/mock.py\", line 786, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_stationary_distribution.StationaryDistribution.test_first", "status": "errored", "message": "list index out of range", "passed": false, "points": ["p07-20.1"], "backtrace": ["  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/anaconda3/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/Users/satu/Kurssit/hy-data-analysis-with-python-spring-2019/part07-e20_stationary_distribution/test/test_stationary_distribution.py\", line 36, in test_first\n    np.testing.assert_allclose(distributions[0], [0.33333333, 0., 0.66666667,  0], atol=1e-04)\n"]}]